### ISSUE TITLE
Edu

### ISSUE THREAD

**Issue by jakubnovak710** [markotomcik/EduPageTestHack#1]
Ahoj, mam otazku. Máš aj kod pre zobrazenie odpovedi pred testom? Vtedy, ked na edu ukazuje, že nie je vhodný čas na spustenie materiálu. Dík :)

**Comment by markotomcik** [comment]
Na zobrazenie odpovedí pred testom môžeš použiť `EdubarUtils.isUcitel = function() {return true;};`. Tento kód vlož **do konzoly** pred tým ako daný test otvoríš (najlepšie je ho tam hodiť keď si **v notifikačnom feede**). Potom už len stačí spraviť to, čo chceš, najlepšie **upraviť materiál**. Problém je, že to vyzerá tak, že Edupage takéto problémy spoločne EduPageTestHackom pomaly **patchuje**, ale zatiaľ to funguje.
