### ISSUE TITLE
kontakt

### ISSUE THREAD

**Issue by KraXen72** [markotomcik/EduPageTestHack#10]
@ivanhrabcak  alebo @markotomcik  mate discord? rad by som sa s vami skontaktoval ohladne tejto temy, myslim ze by som mohol prispiet. moj discord je KraXen72#9190

**Comment by ivanhrabcak** [comment]
ivicek#0357

**Comment by KraXen72** [comment]
poslal som ziadost

**Comment by ZabudniNato** [comment]
Ak chcete viem vam poskytnut testovaciu stranku EduPage.

**Comment by ZabudniNato** [comment]
https://42624333.edupage.org/

**Comment by KraXen72** [comment]
> ivicek#0357

ok poslal som ziadost na priatelstvo moj discord je KraXen72#9190

**Comment by ivanhrabcak** [comment]
> 
> 
> https://42624333.edupage.org/

Si záchranca.

Ako sa ti to podarilo vytvoriť? Viem že v minulosti to išlo ale už neviem ako to ide....

**Comment by markotomcik** [comment]
@ZabudniNato máš dc?

**Comment by ZabudniNato** [comment]
Môj druhý účet je VladonM#3103
A tú stránku som vytvoril tým najabsurdenjším spôsobom. Dúfam, že túto
nezrušila lebo som mal ešte jednu a tú zrušili za 3 dní.

Dňa st 17. 2. 2021, 13:05 Marko Tomčík <notifications@github.com>
napísal(a):

**Comment by jozpac** [comment]
@ivanhrabcak poslal som Ti ziadost na dc. Tiez by som mohol prispiet skusenostami a kodom.
