### ISSUE TITLE
Funguje to naozaj ?

### ISSUE THREAD

**Issue by phifoxd** [markotomcik/EduPageTestHack#3]
Niektore otazky mi ukazalo podla mna zle...
Naozaj je to tak, ze to funguje

**Comment by markotomcik** [comment]
EduPage postupne začal robiť patche svojej stránky. Tzn. že kód bude postupne, ak už nie je, nefunkčný. V budúcnosti je zároveň vysoko pravdepodobné, že podobný kód už nebude nájdený. EduPage posielal správne odpovede klientovi v pozadí, a pochybujem, že takú chybu spraví aj v budúcnosti 😀.

**Comment by phifoxd** [comment]
cize ale stale asi funguje nie ? XD

**Comment by markotomcik** [comment]
Po mojich posledných testoch je výsledok, že nie.
