### ISSUE TITLE
Otázka

### ISSUE THREAD

**Issue by lexXx11** [markotomcik/EduPageTestHack#9]
Nazdar chalani, chcel som sa Vás spýtať nieje vidno keď pouzijem Váš kód.

**Comment by markotomcik** [comment]
Duplicate of #8

**Comment by lexXx11** [comment]
pardon asi som sa zle vyjadril ale myslel som to tak či môžu nejako zistit ze som pouzil vas kod.

**Comment by markotomcik** [comment]
Ten kód pracuje iba u teba na pc - takže nikto iný nevidí, že si ten kód použil.

**Comment by lexXx11** [comment]
nice diki moc fungoval velmi dobre.

**Comment by ivanhrabcak** [comment]
> Nazdar chalani, chcel som sa Vás spýtať nieje vidno keď pouzijem Váš kód.

Nie, kód využíva iba dáta ktoré Edupage posiela klientovi, nerobí žiadne requesty navyše
